# Generated by Django 5.1.3 on 2025-02-01 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signupattemptemail',
            name='account_deleted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 1, 18, 54, 38, 100465, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupattemptipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signupattemptipaddress',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 1, 18, 54, 46, 987599, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
