# Generated by Django 5.1.3 on 2025-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='original_email',
            field=models.EmailField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
