# Generated by Django 5.1.3 on 2025-02-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_original_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='original_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
