# Generated by Django 5.1.3 on 2024-12-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
