# Generated by Django 5.1.3 on 2025-06-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_rename_owner_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
