# Generated by Django 5.1.3 on 2025-06-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
